on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string

jobs:
  run-tests:
    name: Run project tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run tests
        run: python -m unittest -v test_module.py
        working-directory: ${{ inputs.project_path }}
